apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vcy7z5ejc-go 
  janus-idp.io/tekton: vcy7z5ejc-go
  backstage.io/kubernetes-id: vcy7z5ejc-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vcy7z5ejc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml