apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vcy7z5ejc-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:9a66c5c5fba37b1b8d44114b37f2eaeb34fd4e55@sha256:cd81f8e4745ffc26cf05f897fed9b53e2594bc97dc83eece80218b5570532d80
          name: container-image
