apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vcy7z5ejc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vcy7z5ejc-go 
  name: vcy7z5ejc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vcy7z5ejc-go 
